# Simplified working configuration for AI Work Management System
name = "ai-work-mgmt"
main = "src/workers/api-worker.js"
compatibility_date = "2024-01-01"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "ai-work-mgmt-db"
database_id = "ba604ad4-f750-4fbe-b702-e2b698b0dcb6"

[[kv_namespaces]]
binding = "SESSIONS"
id = "d08b2f068c944da1ace819d9441bee68"
preview_id = "a7c52c45db524229b531a2b048233b61"

[vars]
ENVIRONMENT = "development"
# Add this JWT secret (use a strong random string in production)
JWT_SECRET = "2aeb89559ad95a81e27cc08eb09e73ca62b16098065f18f0bf555704575eb8c3d99ce4b5c026a2786a605e22dacd0d97e92325ae6d5c3f12e6536fce4f8bd3bb"