# Simplified working configuration for AI Work Management System
name = "ai-work-mgmt"
main = "src/workers/api-worker.js"
compatibility_date = "2024-01-01"
workers_dev = true

# Replace these with your actual IDs from:
# wrangler d1 create ai-work-mgmt-db
# wrangler kv:namespace create "SESSIONS"
# wrangler kv:namespace create "SESSIONS" --preview

[[d1_databases]]
binding = "DB"
database_name = "ai-work-mgmt-db"
database_id = "ba604ad4-f750-4fbe-b702-e2b698b0dcb6"

[[kv_namespaces]]
binding = "SESSIONS"
id = "d08b2f068c944da1ace819d9441bee68"
preview_id = "a7c52c45db524229b531a2b048233b61"

[vars]
ENVIRONMENT = "development"